apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/VitoAmedeo/gitops-cert-level-2-examples.git
              revision: HEAD
              directories:
                - path: applicationset/examples/matrix/cluster-addons/*
          # cluster generator, 'child' #2
          - clusters: {}

  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/VitoAmedeo/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: application-sets/example-apps/*
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
