apiVersion: batch/v1
kind: Job
metadata:
  namespace: example04
  generateName: my-db-upgrade-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    
